GET https://vbjhkslbynflsvvdiohz.supabase.co/functions/v1/get-customers/b3c034d3-0f43-4d17-9b26-dd5749a86958
authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6Im14TE13UVlNMW9OWjFjRWwiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3Ziamhrc2xieW5mbHN2dmRpb2h6LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJiM2MwMzRkMy0wZjQzLTRkMTctOWIyNi1kZDU3NDlhODY5NTgiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzUzOTQ2NjMyLCJpYXQiOjE3NTM5NDMwMzIsImVtYWlsIjoiYWRhbXNhZ2VlcjAyMkBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoiYWRhbXNhZ2VlcjAyMkBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJzdWIiOiJiM2MwMzRkMy0wZjQzLTRkMTctOWIyNi1kZDU3NDlhODY5NTgifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc1Mzk0MzAzMn1dLCJzZXNzaW9uX2lkIjoiNmVhMzU5MWYtOTFlNC00MTM2LTlkMDctOTc1NmU4N2Q2MmRlIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.zFKoTA9GgR0vHrSGEUGiu0H3V9tqGQAxYMJlk6zFLZE