GET https://vbjhkslbynflsvvdiohz.supabase.co/functions/v1/view-customer-details/306e8830-3310-44be-b553-05d9dfb7de59
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6Im14TE13UVlNMW9OWjFjRWwiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3Ziamhrc2xieW5mbHN2dmRpb2h6LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJiM2MwMzRkMy0wZjQzLTRkMTctOWIyNi1kZDU3NDlhODY5NTgiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzUzOTc2OTE1LCJpYXQiOjE3NTM5NzMzMTUsImVtYWlsIjoiYWRhbXNhZ2VlcjAyMkBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoiYWRhbXNhZ2VlcjAyMkBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJzdWIiOiJiM2MwMzRkMy0wZjQzLTRkMTctOWIyNi1kZDU3NDlhODY5NTgifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc1Mzk3MzMxNX1dLCJzZXNzaW9uX2lkIjoiMTcyMjQzMzAtNWVlZi00ZGZjLTgwNzYtODEyM2JjNzY5YzNlIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.bdShFuIwxF2gvGdDmYC4w1tRiKghRmbhw2bIu-SSsNc